# Generated by Django 5.1.1 on 2024-10-07 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.questionmodel')),
            ],
        ),
    ]
